name: 'Push Script - Leave Request Form'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'scripts/leave-request-form/**'
      - '.github/workflows/push_script_leave_request_form.yaml'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Clasp Push'
        uses: 'daikikatsuragawa/clasp-action@v1.1.0'
        with:
          accessToken: '${{ secrets.CLASP_ACCESS_TOKEN }}'
          idToken: '${{ secrets.CLASP_ID_TOKEN }}'
          refreshToken: '${{ secrets.CLASP_REFRESH_TOKEN }}'
          clientId: '${{ secrets.CLASP_CLIENT_ID }}'
          clientSecret: '${{ secrets.CLASP_CLIENT_SECRET }}'
          scriptId: '${{ secrets.GAS_SCRIPT_ID_LEAVE_REQUEST_FORM }}'
          rootDir: 'scripts/leave-request-form'
          command: 'push'
